### ISSUE TITLE
Feature Request: Runnables

### ISSUE THREAD

**Issue by prashanth-hegde** [lv37/zed-v#1]
### Description

Zed has introduced Runnables, which display a `play` ⏯️ button next to `main()` `test` functions etc to enable easy running of tests and __runnable__ code based on treesitter. 

Would love to see this supported in zed-v as well. 
The changes are simple, just include a `runnables.scm` defining what treesitter components should show the buttons. 

### References: 

- [Blog and details](https://zed.dev/blog/zed-decoded-tasks) (see Runnables section)
- [golang runnables.scm implementation](https://github.com/zed-industries/zed/blob/main/crates/languages/src/go/runnables.scm)
- [golang rs source](https://github.com/zed-industries/zed/blob/main/crates/languages/src/go.rs)

I have zero experience with rust or treesitter. I looked at the code, and it will take me a while to get to the bottom of it to open a PR. So opening a feature request here - in case someone is gracious enough to add it to the repo. 
I have greatly enjoyed coding in V with zed. It's super-stable and helpful.

**Comment by lv37** [comment]
Check out the [README](https://github.com/lv37/zed-v/blob/main/README.md#Runnables) for how to use runnables.
