### ISSUE TITLE
open v-analyzer-darwin-x86_64 outputs "bad CPU type in executable"

### ISSUE THREAD

**Issue by holder66** [lv37/zed-v#13]
After following the instructions to add zed-v to zed on a 2019 macbook pro, zed-v successfully downloads /v-analyzer-darwin-x86_64; however, zed reports this error:
```
Language server error: v

failed to spawn command. path: "/Users/henryolders/Library/Application Support/Zed/extensions/work/v/v-analyzer-darwin-x86_64", working directory: "/Users/henryolders/vhamml", args: []
-- stderr--
```
When I `open /Users/henryolders/Library/Application Support/Zed/extensions/work/v/v-analyzer-darwin-x86_64`, 
I get:
```
/Users/henryolders/Library/Application\ Support/Zed/extensions/work/v/v-analyzer-darwin-x86_64 ; exit;
{24-11-10 21:36}mbp2021:~ henryolders% /Users/henryolders/Library/Application\ Support/Zed/extensions/work/v/v-analyzer-darwin-x86_64 ; exit;
zsh: bad CPU type in executable: /Users/henryolders/Library/Application Support/Zed/extensions/work/v/v-analyzer-darwin-x86_64

Saving session...completed.

[Process completed]
```

I tried installing v-analyzer, using this command:
`v -e "$(curl -fsSL https://raw.githubusercontent.com/v-analyzer/v-analyzer/main/install.vsh)"`
And added it to $PATH. 
The command `open /Users/henryolders/.config/v-analyzer/bin/v-analyzer` gives:
```
/Users/henryolders/.config/v-analyzer/bin/v-analyzer ; exit;
{24-11-10 21:49}mbp2021:~ henryolders% /Users/henryolders/.config/v-analyzer/bin/v-analyzer ; exit;
```

So it seems that the generic binary of v-analyzer runs on my machine, but the architecture-specific binary does not.

**Comment by spytheman** [comment]
The repository for v-analyzer is now <https://github.com/vlang/v-analyzer> and the updated version can be installed with this command (on linux/macos):

`v -e "$(curl -fsSL https://raw.githubusercontent.com/vlang/v-analyzer/main/install.vsh)"`

**Comment by lv37** [comment]
It was downloading the the wrong binary. It should be fixed now.

Delete `/Users/henryolders/Library/Application Support/Zed/extensions/work/v/v-analyzer-darwin-x86_64` and it should automatically download the right one.
