### ISSUE TITLE
Integrated v-analyzer

### ISSUE THREAD

**Issue by Avey777** [lv37/zed-v#4]
https://github.com/vlang/v-analyzer

It would be nice if v-analyzer could be integrated into zed-v. We only need to download the plugin and the rest will be done automatically.

**Comment by Avey777** [comment]
![image](https://github.com/lv37/zed-v/assets/35259040/5e4ad3ac-3d40-438a-bccd-fa90a289e56a)
Can't  go to difinition

**Comment by lv37** [comment]
The extension already tries to download `v-analyzer` from [GitHub Releases](https://github.com/v-analyzer/v-analyzer/releases). But it fails to find binaries for some systems that are not listen on `v-analyzer`'s release page (for example: it fails to download it on aarch64 Linux)

**Comment by lv37** [comment]
> Can't go to difinition

That's probably a bug in `v-analyzer` itself. Report that issue on their github
