### ISSUE TITLE
Is zed configuring v-analyzer in setting.json?

### ISSUE THREAD

**Issue by Avey777** [lv37/zed-v#5]
![image](https://github.com/lv37/zed-v/assets/35259040/5c99a3ba-0007-4201-bbe1-4fd2a7500277)

![image](https://github.com/lv37/zed-v/assets/35259040/8f54c8d5-6320-4e26-8d50-a6fe43725f13)

I configured it like this, but I still can’t “go to definition” in zed

**Comment by lv37** [comment]
The `v-analyzer.serverPath` setting is not using by anything. You should just remove it. As for `go to definition` not working, it's a known bug with `v-analyzer` (https://github.com/vlang/v-analyzer/issues/105) so there's not really anything I can do to fix it.
