### ISSUE TITLE
Please write details user guilde for benginer, Thank you.

### ISSUE THREAD

**Issue by changrui** [lv37/zed-v#6]

**Comment by lv37** [comment]
Using the extensions should be pretty straightforward and uncomplicated. Make sure to read the [`README`](https://github.com/lv37/zed-v/blob/main/README.md) and the [Zed docs](https://zed.dev/docs/configuring-zed).

**Comment by duarteroso** [comment]
It is not clear how the language support is added. Unless this extensions only adds runnables?
If you could provide some help around that, we'd be forever grateful :)

**Comment by lv37** [comment]
The extension has built-in syntax highlighting. Code completion, however, requires [`v-analyzer`](https://github.com/vlang/v-analyzer) to be installed and visible in your system's [`PATH`](https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them).

**Comment by lv37** [comment]
So all you have to do is have `v-analyzer` installed on your system and added to your PATH.

**Comment by shininglove** [comment]
Had a bit of difficulty with this until I realized, this was already hosted as an extension for zed. Just have to do Ctrl+Shift+P and type extensions and search for 'V' and click install
